// Generated by gencpp from file custom_behavior_actions/DriveForward.msg
// DO NOT EDIT!


#ifndef CUSTOM_BEHAVIOR_ACTIONS_MESSAGE_DRIVEFORWARD_H
#define CUSTOM_BEHAVIOR_ACTIONS_MESSAGE_DRIVEFORWARD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_behavior_actions
{
template <class ContainerAllocator>
struct DriveForward_
{
  typedef DriveForward_<ContainerAllocator> Type;

  DriveForward_()
    : distance(0.0)  {
    }
  DriveForward_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::custom_behavior_actions::DriveForward_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_behavior_actions::DriveForward_<ContainerAllocator> const> ConstPtr;

}; // struct DriveForward_

typedef ::custom_behavior_actions::DriveForward_<std::allocator<void> > DriveForward;

typedef boost::shared_ptr< ::custom_behavior_actions::DriveForward > DriveForwardPtr;
typedef boost::shared_ptr< ::custom_behavior_actions::DriveForward const> DriveForwardConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_behavior_actions::DriveForward_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_behavior_actions::DriveForward_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_behavior_actions::DriveForward_<ContainerAllocator1> & lhs, const ::custom_behavior_actions::DriveForward_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_behavior_actions::DriveForward_<ContainerAllocator1> & lhs, const ::custom_behavior_actions::DriveForward_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_behavior_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_behavior_actions::DriveForward_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_behavior_actions::DriveForward_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_behavior_actions::DriveForward_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_behavior_actions::DriveForward_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_behavior_actions::DriveForward_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_behavior_actions::DriveForward_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_behavior_actions::DriveForward_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::custom_behavior_actions::DriveForward_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_behavior_actions::DriveForward_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_behavior_actions/DriveForward";
  }

  static const char* value(const ::custom_behavior_actions::DriveForward_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_behavior_actions::DriveForward_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Custom message for driving forward\n"
"float32 distance    # Distance to drive forward (in meters)\n"
"\n"
;
  }

  static const char* value(const ::custom_behavior_actions::DriveForward_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_behavior_actions::DriveForward_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveForward_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_behavior_actions::DriveForward_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_behavior_actions::DriveForward_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_BEHAVIOR_ACTIONS_MESSAGE_DRIVEFORWARD_H
