// Generated by gencpp from file custom_behavior_actions/DriveForwardGoal.msg
// DO NOT EDIT!


#ifndef CUSTOM_BEHAVIOR_ACTIONS_MESSAGE_DRIVEFORWARDGOAL_H
#define CUSTOM_BEHAVIOR_ACTIONS_MESSAGE_DRIVEFORWARDGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_behavior_actions
{
template <class ContainerAllocator>
struct DriveForwardGoal_
{
  typedef DriveForwardGoal_<ContainerAllocator> Type;

  DriveForwardGoal_()
    : speed(0)  {
    }
  DriveForwardGoal_(const ContainerAllocator& _alloc)
    : speed(0)  {
  (void)_alloc;
    }



   typedef int64_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DriveForwardGoal_

typedef ::custom_behavior_actions::DriveForwardGoal_<std::allocator<void> > DriveForwardGoal;

typedef boost::shared_ptr< ::custom_behavior_actions::DriveForwardGoal > DriveForwardGoalPtr;
typedef boost::shared_ptr< ::custom_behavior_actions::DriveForwardGoal const> DriveForwardGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator1> & lhs, const ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator1> & lhs, const ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_behavior_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4734ede392d478601ffe9898680ff4b5";
  }

  static const char* value(const ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4734ede392d47860ULL;
  static const uint64_t static_value2 = 0x1ffe9898680ff4b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_behavior_actions/DriveForwardGoal";
  }

  static const char* value(const ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal         \n"
"int64 speed\n"
;
  }

  static const char* value(const ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveForwardGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_behavior_actions::DriveForwardGoal_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_BEHAVIOR_ACTIONS_MESSAGE_DRIVEFORWARDGOAL_H
