(cl:defpackage custom_behavior_actions-msg
  (:use )
  (:export
   "<DRIVEFORWARD>"
   "DRIVEFORWARD"
   "<DRIVEFORWARDACTION>"
   "DRIVEFORWARDACTION"
   "<DRIVEFORWARDACTIONFEEDBACK>"
   "DRIVEFORWARDACTIONFEEDBACK"
   "<DRIVEFORWARDACTIONGOAL>"
   "DRIVEFORWARDACTIONGOAL"
   "<DRIVEFORWARDACTIONRESULT>"
   "DRIVEFORWARDACTIONRESULT"
   "<DRIVEFORWARDFEEDBACK>"
   "DRIVEFORWARDFEEDBACK"
   "<DRIVEFORWARDGOAL>"
   "DRIVEFORWARDGOAL"
   "<DRIVEFORWARDRESULT>"
   "DRIVEFORWARDRESULT"
  ))

