; Auto-generated. Do not edit!


(cl:in-package custom_behavior_actions-msg)


;//! \htmlinclude DriveForwardGoal.msg.html

(cl:defclass <DriveForwardGoal> (roslisp-msg-protocol:ros-message)
  ((speed
    :reader speed
    :initarg :speed
    :type cl:integer
    :initform 0))
)

(cl:defclass DriveForwardGoal (<DriveForwardGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveForwardGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveForwardGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name custom_behavior_actions-msg:<DriveForwardGoal> is deprecated: use custom_behavior_actions-msg:DriveForwardGoal instead.")))

(cl:ensure-generic-function 'speed-val :lambda-list '(m))
(cl:defmethod speed-val ((m <DriveForwardGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader custom_behavior_actions-msg:speed-val is deprecated.  Use custom_behavior_actions-msg:speed instead.")
  (speed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveForwardGoal>) ostream)
  "Serializes a message object of type '<DriveForwardGoal>"
  (cl:let* ((signed (cl:slot-value msg 'speed)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveForwardGoal>) istream)
  "Deserializes a message object of type '<DriveForwardGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'speed) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveForwardGoal>)))
  "Returns string type for a message object of type '<DriveForwardGoal>"
  "custom_behavior_actions/DriveForwardGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveForwardGoal)))
  "Returns string type for a message object of type 'DriveForwardGoal"
  "custom_behavior_actions/DriveForwardGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveForwardGoal>)))
  "Returns md5sum for a message object of type '<DriveForwardGoal>"
  "4734ede392d478601ffe9898680ff4b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveForwardGoal)))
  "Returns md5sum for a message object of type 'DriveForwardGoal"
  "4734ede392d478601ffe9898680ff4b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveForwardGoal>)))
  "Returns full string definition for message of type '<DriveForwardGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal         ~%int64 speed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveForwardGoal)))
  "Returns full string definition for message of type 'DriveForwardGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal         ~%int64 speed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveForwardGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveForwardGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveForwardGoal
    (cl:cons ':speed (speed msg))
))
