// Generated by gencpp from file gazebo_launch/DriveForwardFeedback.msg
// DO NOT EDIT!


#ifndef GAZEBO_LAUNCH_MESSAGE_DRIVEFORWARDFEEDBACK_H
#define GAZEBO_LAUNCH_MESSAGE_DRIVEFORWARDFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_launch
{
template <class ContainerAllocator>
struct DriveForwardFeedback_
{
  typedef DriveForwardFeedback_<ContainerAllocator> Type;

  DriveForwardFeedback_()
    : progress(0.0)  {
    }
  DriveForwardFeedback_(const ContainerAllocator& _alloc)
    : progress(0.0)  {
  (void)_alloc;
    }



   typedef float _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DriveForwardFeedback_

typedef ::gazebo_launch::DriveForwardFeedback_<std::allocator<void> > DriveForwardFeedback;

typedef boost::shared_ptr< ::gazebo_launch::DriveForwardFeedback > DriveForwardFeedbackPtr;
typedef boost::shared_ptr< ::gazebo_launch::DriveForwardFeedback const> DriveForwardFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator1> & lhs, const ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator1> & lhs, const ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_launch

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70805092fd20e110765c7b79e8efb737";
  }

  static const char* value(const ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70805092fd20e110ULL;
  static const uint64_t static_value2 = 0x765c7b79e8efb737ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_launch/DriveForwardFeedback";
  }

  static const char* value(const ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 progress\n"
;
  }

  static const char* value(const ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveForwardFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_launch::DriveForwardFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_LAUNCH_MESSAGE_DRIVEFORWARDFEEDBACK_H
